;; This logfile was generated automatically by `xindy'
;; at 01.06.2026  14:00:19
;; Indexstyle: "/tmp/KMidH80OkY", Rawindex: "/tmp/ar2HWwk0vv", Output: "00_Abschlussarbeit.acr"


Building indexentry-tree:
Hierdepth of index is :TREE

sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)

Forming letter-groups:
Letter-group: "à€å" -> "U"
Letter-group: "´¨ÈÃ" -> "L"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "´¨ÈÃ" -> "L"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "à€å" -> "U"