;; This logfile was generated automatically by `xindy'
;; at 02.06.2026  22:12:06
;; Indexstyle: "/tmp/U9ICCEBHfL", Rawindex: "/tmp/B3dnX62iuR", Output: "00_Abschlussarbeit.acr"


Building indexentry-tree:
Hierdepth of index is :TREE

sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)

Forming letter-groups:
Letter-group: "à€å" -> "U"
Letter-group: "´¨ÈÃ" -> "L"
Letter-group: "¨»à" -> "I"
Letter-group: "ÈÐ" -> "G"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "ÈÐ" -> "G"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "¨»à" -> "I"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "´¨ÈÃ" -> "L"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "à€å" -> "U"